# -*- coding: utf-8 -*-
"""tensorboard_scalar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWtKehCbSGoA07xKe06dzkR_eKOPK7-p
"""

# Tensorflow Scalar

import tensorflow as tf

tf.reset_default_graph()

# randomly pick 100 value from a normal distribution

s_scalar=tf.get_variable(name="s_scalar",shape=[],initializer=tf.truncated_normal_initializer(mean=0,stddev=1))

first_summary=tf.summary.scalar(name="first_summary", tensor=s_scalar)

init=tf.global_variables_initializer()

with tf.Session() as sess:
    writer=tf.summary.FileWriter( './logs',sess.graph)
    for i in range (100) :
        sess.run(init)
        summary=sess.run(first_summary)
        writer.add_summary(summary,i)